# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0

arc:
  ai:
    clients:
      - id: GPT4o-mini
        modelName: gpt-4o-mini
        client: "openai"
        apiKey: ${OPENAI_API_KEY}
        url: https://api.openai.com/v1/

#//google search engine config
google:
  search.engine.key: ${SEARCH_ENGINE_KEY:}
  cloud.api.key: ${CLOUD_KEY:}